### ISSUE TITLE
Uncaught Error: Cannot find module './game-maker-view'

### ISSUE THREAD

**Issue by MaximumCrash** [coppolaemilio/language-gml#3] opened 2015-12-29 00:36 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Home
**Thrown From**: [language-gml](https://github.com/coppolaemilio/language-gml) package, v0.2.2
### Stack Trace

Uncaught Error: Cannot find module './game-maker-view'

```
At module.js:338

Error: Cannot find module './game-maker-view'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Rejon/.atom/packages/language-gml/lib/language-gml.coffee:1:17)
    at Object.<anonymous> (file:///C:/Users/Rejon/.atom/packages/language-gml/lib/language-gml.coffee:1:1)
    at Module._compile (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
    at Package.module.exports.Package.activateConfig (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:188:14)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:171:21)
    at C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:302:17
    at Emitter.module.exports.Emitter.emit (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:664:27)
    at C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:26
    at exit (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Rejon\AppData\Local\atom\app-1.3.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -0:31.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "min-ui",
      "monokai-verbose-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
AtLilyPond, v1.2.0
min-ui, v0.0.1
monokai-verbose-syntax, v0.1.1
shadow, v0.1.0

# Dev
No dev packages
```

**Comment by coppolaemilio** [comment] 2015-12-31 18:46
I cannot reproduce this issue, have you tried re-installing the plugin?

**Comment by kiesenverseist** [comment] 2016-05-26 12:17
I am also getting this issue.
It happens when I am in the settings tab and i click on the packages section and then click on this package. This only happens the first time i click on the package from starting up the atom editor. If i try again this error does not show up again until i restart the app.

**Comment by Vercaelus** [comment] 2016-09-14 18:54
This is an issue for me as well.

**Comment by Lerrrtaste** [comment] 2016-10-18 22:17
I´m also getting this error. Installed Atom the first time on Win10 and this is the first Package I install and also the first thing i do in Atom (No Settings changed, Files created...)

Error report:

> [Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: [language-gml](https://github.com/coppolaemilio/language-gml) package, v0.3.0

### Stack Trace

Uncaught Error: Cannot find module './game-maker-view'

```
At module.js:341

Error: Cannot find module './game-maker-view'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/lf200/.atom/packages/language-gml/lib/language-gml.coffee:1:17)
    at Object.<anonymous> (file:///C:/Users/lf200/.atom/packages/language-gml/lib/language-gml.coffee:1:1)
    at Module._compile (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at Package.module.exports.Package.activateConfig (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:225:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:55:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:699:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:397:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:390:12)
    at C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:643:24
    at C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:712:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:680:27)
    at C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:468:26
    at exit (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\lf200\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
     -1:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

``` coffee
# User
language-gml, v0.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by coppolaemilio** [comment] 2016-10-29 16:15
I pushed a new version, please confirm that it fixed the issue so I can close this ticket. Sorry for the delay!

**Comment by kiesenverseist** [comment] 2016-11-05 05:13
It seems to be working fine now! Thank you.

Also you probably already know but game maker studio 2 is now a thing which brings with it an updated language. To go with that they did improve the inbuilt editor, in case you didn't already know.

**Comment by coppolaemilio** [comment] 2016-11-05 09:07
@kiesenverseist Thanks!
About studio 2, I don't think I will be using it. I'm moving to Godot since it is open source and I'm contributing on its development. Cheers!

**Closed as completed by coppolaemilio** 2016-11-05 09:07 UTC
